function Am=appendmirror(A)


l=size(A,1);
Afl=flipud(A);
Abeg=repmat(2*A(1,:),[l,1])-Afl;
Aend=repmat(2*A(end,:),[l,1])-Afl;
Am=[...
        Abeg(1,:);...
        Abeg((1:(end-1)),:);...
        A;...
        Aend((2:end),:);...
        Aend(end,:)...
    ];